---
root: true

env:
  es6: true
  node: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

parserOptions:
  ecmaVersion: 2020
  sourceType: module
  ecmaFeatures:
    globalReturn: true

rules:
  no-with: error
  no-unexpected-multiline: error
  array-bracket-spacing: 
    - error
    - never
  no-duplicate-imports: error
  default-param-last: error
  default-case-last: warn
  space-in-parens: 
    - error
    - never
  no-unsafe-negation: error
  no-extra-boolean-cast: error
  no-sparse-arrays: error
  no-new-wrappers: error
  no-multiple-empty-lines: 
    - error
    - 
      max: 2
      maxEOF: 1
      maxBOF: 0
  no-extend-native: error
  no-func-assign: error
  no-unreachable: error
  no-dupe-args: error
  no-var: error
  no-debugger: error
  no-new-func: error
  no-dupe-keys: error
  getter-return: error
  no-extra-semi: error
  for-direction: error
  arrow-spacing: 
    - error
    -
      before: true
      after: true 
  brace-style: 
    - error
    - 1tbs
  use-isnan: warn
  no-caller: error
  no-empty: error
  indent: 
    - error
    - 4
    - 
      SwitchCase: 1
  quotes: 
    - error
    - single
  semi: 
    - error
    - always
  yoda: error

  '@typescript-eslint/adjacent-overload-signatures': warn
  '@typescript-eslint/consistent-type-definitions': 
    - error
    - interface
  '@typescript-eslint/no-array-constructor': 'error'
  '@typescript-eslint/no-empty-interface': 'error'
  '@typescript-eslint/no-empty-function': 'error'
  '@typescript-eslint/prefer-as-const': 'error'
  '@typescript-eslint/no-extra-semi': 'error'
  '@typescript-eslint/no-namespace': 
    - error
    -
      allowDeclarations: true
  '@typescript-eslint/brace-style': 
    - error
    - 1tbs
  '@typescript-eslint/array-type': error
  '@typescript-eslint/ban-types':
    - warn
    -
      types:
        Number:
          message: Use the 'number' type instead
          fixWith: number
        String:
          message: Use the 'string' type instead
          fixWith: string
        '{}':
          message: Use type Record<string, unknown> instead
          fixWith: object